### PR TITLE
Add function to wait for and get the next mail

### PR DESCRIPTION
**Pull request by a15923647**
1. Add argument, once, to monitor function, which enabling referenced functions to wait for a mail and make further process.
2. Add try except clause to pyperclip.copy so that it will not raise error when one is using ssh terminal.

### CODE REVIEW

**Comment by CarloDePieri** [comment]
Thank you for contributing!

I see the merit in having a function that waits for the next mail and returns it: I'll make sure to introduce it even in the next version I'm working on.

In the meantime, I would rather separate concerns rather than add one to the `monitor_account` and to the `monitor_new_account` methods. In the `Account` class, something like:

```python
    def wait_for_next_message(self):
        start = len(self.get_messages())
        while len(self.get_messages()) == start:
            sleep(1)
        return self.get_messages()[0]

    def monitor_account(self):
        while True:
            print("\nWaiting for new messages...")
            message = self.wait_for_next_message()
            print("New message arrived!")
            message.open_web()
```

To wait and get the next mail you would then:

```python
account = MailTm()._open_account()
next_mail = account.wait_for_next_message()
```

Would this address your intended use case?

**Comment by a15923647** [comment]
Yes, this is what I'm looking for. Your solution makes more sense.

**Comment by CarloDePieri** [comment]
Alright!

I implemented the new features with the relative tests.

CI can't pass directly from here since it's a fork branch and it does not have access to secrets, but [it did pass CI in a review branch](https://github.com/CarloDePieri/pymailtm/actions/runs/2747912563), so if you have nothing to add I'd merge this PR.

**Comment by a15923647** [comment]
Ok. Thanks.

**Pull request merged**
